-- MySQL Script generated by MySQL Workbench
-- Wed May 07 15:31:42 2020
-- Model: New Model Version: 1.0
-- MySQL Workbench Forward Engineering
SET @OLD_UNIQUE_CHECKS = @@UNIQUE_CHECKS, UNIQUE_CHECKS = 0;
SET @OLD_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS = 0;
SET @OLD_SQL_MODE = @@SQL_MODE,SQL_MODE =
        'ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
-- -----------------------------------------------------
-- Schema smartmaintenance
-- -----------------------------------------------------
USE `smartmaintenance`;
-- -----------------------------------------------------
-- Table `entity_class`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `entity_class`;
CREATE TABLE IF NOT EXISTS `entity_class`
(
    `id_entity_class` INT         NOT NULL AUTO_INCREMENT,
    `name`            VARCHAR(45) NULL,
    PRIMARY KEY (`id_entity_class`)
)
    ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table `entity`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `entity`;
CREATE TABLE IF NOT EXISTS `entity`
(
    `id_entity`       INT         NOT NULL AUTO_INCREMENT,
    `name`            VARCHAR(45) NULL,
    `description`     VARCHAR(45) NULL,
    `id_entity_class` INT         NOT NULL,
    PRIMARY KEY (`id_entity`),
    CONSTRAINT `fk_entity_entity_class1`
        FOREIGN KEY (`id_entity_class`)
            REFERENCES `entity_class` (`id_entity_class`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;
CREATE INDEX `fk_entity_entity_class1_idx` ON `entity` (`id_entity_class`
                                                        ASC);
-- -----------------------------------------------------
-- Table `property`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `property`;
CREATE TABLE IF NOT EXISTS `property`
(
    `id_property` INT         NOT NULL AUTO_INCREMENT,
    `name`        VARCHAR(45) NULL,
    PRIMARY KEY (`id_property`)
)
    ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table `entities_class_properties`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `entities_class_properties`;
CREATE TABLE IF NOT EXISTS `entities_class_properties`
(
    `id_entity_class` INT NOT NULL,
    `id_property`     INT NOT NULL,
    PRIMARY KEY (`id_entity_class`, `id_property`),
    CONSTRAINT `fk_property_has_entity_class_property1`
        FOREIGN KEY (`id_property`)
            REFERENCES `property` (`id_property`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `fk_property_has_entity_class_entity_class1`
        FOREIGN KEY (`id_entity_class`)
            REFERENCES `entity_class` (`id_entity_class`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;
CREATE INDEX `fk_property_has_entity_class_entity_class1_idx` ON
    `entities_class_properties` (`id_entity_class` ASC);
CREATE INDEX `fk_property_has_entity_class_property1_idx` ON
    `entities_class_properties` (`id_property` ASC);
-- -----------------------------------------------------
-- Table `entities_properties`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `entities_properties`;
CREATE TABLE IF NOT EXISTS `entities_properties`
(
    `id_entity`   INT         NOT NULL,
    `id_property` INT         NOT NULL,
    `value`       VARCHAR(45) NULL,
    PRIMARY KEY (`id_entity`, `id_property`),
    CONSTRAINT `fk_property_has_entity_property1`
        FOREIGN KEY (`id_property`)
            REFERENCES `property` (`id_property`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `fk_property_has_entity_entity1`
        FOREIGN KEY (`id_entity`)
            REFERENCES `entity` (`id_entity`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;
CREATE INDEX `fk_property_has_entity_entity1_idx` ON `entities_properties`
    (`id_entity` ASC);
CREATE INDEX `fk_property_has_entity_property1_idx` ON `entities_properties`
    (`id_property` ASC);
-- -----------------------------------------------------
-- Table `hierarchy`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hierarchy`;
CREATE TABLE IF NOT EXISTS `hierarchy`
(
    `id_entity` INT NOT NULL,
    `id_parent` INT NOT NULL,
    PRIMARY KEY (`id_entity`, `id_parent`),
    CONSTRAINT `fk_pippo_entity1`
        FOREIGN KEY (`id_entity`)
            REFERENCES `entity` (`id_entity`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `fk_pippo_entity2`
        FOREIGN KEY (`id_parent`)
            REFERENCES `entity` (`id_entity`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;
CREATE INDEX `fk_pippo_entity2_idx` ON `hierarchy` (`id_parent` ASC);
SET SQL_MODE = @OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS = @OLD_UNIQUE_CHECKS;